ALTER TABLE research_task
    ADD COLUMN IF NOT EXISTS source_task_id VARCHAR(64) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS source_report_id VARCHAR(64) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS source_domain VARCHAR(64) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS source_review_status VARCHAR(32) DEFAULT NULL,
    ADD COLUMN IF NOT EXISTS analysis_scope VARCHAR(64) DEFAULT NULL;
