USE quant_ai;

CREATE TABLE IF NOT EXISTS market_event_relation (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    event_id VARCHAR(64) NOT NULL,
    relation_type VARCHAR(32) NOT NULL,
    relation_code VARCHAR(64) NOT NULL,
    relation_name VARCHAR(255) DEFAULT NULL,
    relation_weight DECIMAL(8,4) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    UNIQUE KEY uk_event_relation (event_id, relation_type, relation_code),
    INDEX idx_event_id (event_id),
    INDEX idx_relation_code (relation_code)
);

CREATE TABLE IF NOT EXISTS market_event_analysis (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    analysis_id VARCHAR(64) NOT NULL UNIQUE,
    event_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) DEFAULT NULL,
    analysis_version VARCHAR(32) NOT NULL DEFAULT '1.0',
    impact_direction VARCHAR(32) DEFAULT NULL,
    impact_level VARCHAR(32) DEFAULT NULL,
    short_term_view TEXT,
    mid_term_view TEXT,
    risk_flag TINYINT NOT NULL DEFAULT 0,
    confidence_score DECIMAL(5,4) DEFAULT NULL,
    analysis_summary TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    trace_id VARCHAR(128) DEFAULT NULL,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_event_id (event_id),
    INDEX idx_task_id (task_id),
    INDEX idx_status (status),
    INDEX idx_impact_level (impact_level)
);

CREATE TABLE IF NOT EXISTS risk_warning (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    warning_id VARCHAR(64) NOT NULL UNIQUE,
    task_id VARCHAR(64) DEFAULT NULL,
    warning_type VARCHAR(64) NOT NULL,
    warning_level VARCHAR(32) NOT NULL,
    entity_type VARCHAR(32) NOT NULL DEFAULT 'STOCK',
    entity_code VARCHAR(64) NOT NULL,
    entity_name VARCHAR(255) DEFAULT NULL,
    portfolio_id VARCHAR(64) DEFAULT NULL,
    trigger_source VARCHAR(64) DEFAULT NULL,
    trigger_event_id VARCHAR(64) DEFAULT NULL,
    warning_summary TEXT,
    warning_reason TEXT,
    suggest_action TEXT,
    confidence_score DECIMAL(5,4) DEFAULT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    review_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    reviewer_id VARCHAR(64) DEFAULT NULL,
    review_time DATETIME DEFAULT NULL,
    trace_id VARCHAR(128) DEFAULT NULL,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_task_id (task_id),
    INDEX idx_entity_level (entity_code, warning_level),
    INDEX idx_status_review (status, review_status),
    INDEX idx_trigger_event_id (trigger_event_id),
    INDEX idx_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS risk_warning_detail (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    detail_id VARCHAR(64) NOT NULL UNIQUE,
    warning_id VARCHAR(64) NOT NULL,
    indicator_code VARCHAR(64) DEFAULT NULL,
    indicator_name VARCHAR(128) DEFAULT NULL,
    indicator_value VARCHAR(128) DEFAULT NULL,
    threshold_value VARCHAR(128) DEFAULT NULL,
    comparison_result VARCHAR(64) DEFAULT NULL,
    detail_desc TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_warning_id (warning_id),
    INDEX idx_indicator_code (indicator_code)
);

CREATE TABLE IF NOT EXISTS strategy_signal (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    signal_id VARCHAR(64) NOT NULL UNIQUE,
    task_id VARCHAR(64) DEFAULT NULL,
    signal_type VARCHAR(64) NOT NULL,
    entity_code VARCHAR(64) NOT NULL,
    entity_name VARCHAR(255) DEFAULT NULL,
    signal_date DATE DEFAULT NULL,
    signal_score INT DEFAULT NULL,
    signal_level VARCHAR(32) DEFAULT NULL,
    signal_direction VARCHAR(32) DEFAULT NULL,
    reason_summary TEXT,
    confidence_score DECIMAL(5,4) DEFAULT NULL,
    source_event_id VARCHAR(64) DEFAULT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    trace_id VARCHAR(128) DEFAULT NULL,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_task_id (task_id),
    INDEX idx_entity_signal_date (entity_code, signal_date),
    INDEX idx_direction_level (signal_direction, signal_level),
    INDEX idx_source_event_id (source_event_id),
    INDEX idx_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS strategy_signal_factor (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    factor_id VARCHAR(64) NOT NULL UNIQUE,
    signal_id VARCHAR(64) NOT NULL,
    factor_code VARCHAR(64) DEFAULT NULL,
    factor_name VARCHAR(128) DEFAULT NULL,
    factor_value VARCHAR(128) DEFAULT NULL,
    factor_weight DECIMAL(8,4) DEFAULT NULL,
    factor_conclusion TEXT,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_signal_id (signal_id),
    INDEX idx_factor_code (factor_code)
);

CREATE TABLE IF NOT EXISTS report_evidence_ref (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    evidence_id VARCHAR(64) NOT NULL UNIQUE,
    report_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) DEFAULT NULL,
    section_code VARCHAR(64) DEFAULT NULL,
    conclusion_code VARCHAR(64) DEFAULT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_ref_id VARCHAR(128) DEFAULT NULL,
    evidence_summary TEXT,
    evidence_url VARCHAR(512) DEFAULT NULL,
    confidence_score DECIMAL(5,4) DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_report_id (report_id),
    INDEX idx_task_id (task_id),
    INDEX idx_source_ref (source_type, source_ref_id)
);

CREATE TABLE IF NOT EXISTS ai_prompt_audit (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    prompt_audit_id VARCHAR(64) NOT NULL UNIQUE,
    task_id VARCHAR(64) NOT NULL,
    execution_id VARCHAR(64) DEFAULT NULL,
    agent_code VARCHAR(64) NOT NULL,
    prompt_template_code VARCHAR(128) DEFAULT NULL,
    model_name VARCHAR(128) DEFAULT NULL,
    model_version VARCHAR(64) DEFAULT NULL,
    input_digest TEXT,
    prompt_digest TEXT,
    response_digest TEXT,
    token_usage JSON DEFAULT NULL,
    risk_flag TINYINT NOT NULL DEFAULT 0,
    audit_status VARCHAR(32) NOT NULL DEFAULT 'SUCCESS',
    trace_id VARCHAR(128) DEFAULT NULL,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_task_id (task_id),
    INDEX idx_execution_id (execution_id),
    INDEX idx_agent_code (agent_code),
    INDEX idx_audit_status (audit_status)
);

CREATE TABLE IF NOT EXISTS human_review_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    review_id VARCHAR(64) NOT NULL UNIQUE,
    task_id VARCHAR(64) DEFAULT NULL,
    related_object_type VARCHAR(64) NOT NULL,
    related_object_id VARCHAR(64) NOT NULL,
    reviewer_id VARCHAR(64) DEFAULT NULL,
    reviewer_role VARCHAR(64) DEFAULT NULL,
    review_result VARCHAR(32) NOT NULL,
    review_comment VARCHAR(1000) DEFAULT NULL,
    before_snapshot_ref VARCHAR(512) DEFAULT NULL,
    after_snapshot_ref VARCHAR(512) DEFAULT NULL,
    before_snapshot JSON DEFAULT NULL,
    after_snapshot JSON DEFAULT NULL,
    trace_id VARCHAR(128) DEFAULT NULL,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_task_id (task_id),
    INDEX idx_related_object (related_object_type, related_object_id),
    INDEX idx_reviewer_id (reviewer_id),
    INDEX idx_review_result (review_result)
);

CREATE TABLE IF NOT EXISTS task_message_log (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    message_log_id VARCHAR(64) NOT NULL UNIQUE,
    message_id VARCHAR(64) NOT NULL,
    task_id VARCHAR(64) DEFAULT NULL,
    event_id VARCHAR(64) DEFAULT NULL,
    topic_name VARCHAR(128) NOT NULL,
    message_type VARCHAR(64) NOT NULL,
    producer_service VARCHAR(128) DEFAULT NULL,
    consumer_service VARCHAR(128) DEFAULT NULL,
    consume_status VARCHAR(32) NOT NULL,
    retry_count INT NOT NULL DEFAULT 0,
    error_message VARCHAR(1000) DEFAULT NULL,
    raw_message_ref VARCHAR(512) DEFAULT NULL,
    message_timestamp BIGINT DEFAULT NULL,
    trace_id VARCHAR(128) DEFAULT NULL,
    tenant_id VARCHAR(64) NOT NULL DEFAULT 'default',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted TINYINT NOT NULL DEFAULT 0,
    INDEX idx_message_id (message_id),
    INDEX idx_task_id (task_id),
    INDEX idx_event_id (event_id),
    INDEX idx_topic_status (topic_name, consume_status),
    INDEX idx_trace_id (trace_id),
    INDEX idx_created_at (created_at)
);
